#version 450

struct Particle
{
  vec2 position;
  vec3 color;
  vec2 velocity;
};

layout(std430, binding = 0) buffer ParticleBuffer
{
  Particle particles[];
};
layout(std430, binding = 0) buffer CellHead
{
  int cellHeads[];
};

layout(push_constant) uniform PushConstants
{
  uint initialize;
  vec2 screenSize;
  float deltaTime;
};

layout(local_size_x = 256) in;

uint hash(uint x)
{
  x ^= x >> 16;
  x *= 0x7feb352du;
  x ^= x >> 15;
  x *= 0x846ca68bu;
  x ^= x >> 16;
  return x;
}

float randomFloat(uint x)
{
  return float(hash(x)) / 4294967295.0f;
}

float pixelsToNDC(int n, int reference)
{
  return float(n) * (2 / float(reference));
}

const uint GRIDWIDTH = 50;
const uint GRIDHEIGHT = 50;

uvec2 getCell(vec2 position)
{
  vec2 normalized = position * 0.5 + 0.5;

  uint x = uint(normalized.x * GRIDWIDTH);
  uint y = uint(normalized.y * GRIDHEIGHT);

  x = min(x, GRIDWIDTH - 1);
  y = min(y, GRIDHEIGHT - 1);

  return uvec2(x, y);
}

uint getCellIndex(uvec2 cell)
{
  return cell.y * GRIDWIDTH + cell.x;
}

void main()
{
  uint i = gl_GlobalInvocationID.x;
  if(i >= particles.length())
    return;

  if(initialize == 0)
  {
    if(i < cellHeads.length())
      cellHeads[i] = -1;

    return;
  }
  else if(initialize == 1)
  {
    uint count = particles.length();
    float aspect = screenSize.x / screenSize.y;

    uint gridWidth = uint(ceil(sqrt(float(count) * aspect)));
    uint gridHeight = uint(ceil(float(count) / float(gridWidth)));
    uint x = i % gridWidth;
    uint y = i / gridWidth;

    particles[i].position = vec2(
      (float(x) + 0.5) / float(gridWidth) * 2.0 - 1.0,
      (float(y) + 0.5) / float(gridHeight) * 2.0 - 1.0
    );

    particles[i].color = vec3(
      randomFloat(i),
      randomFloat(i + 1),
      randomFloat(i + 2)
    );
    
    particles[i].velocity = vec2(0.0f, 0.0f);
    return;
  }

  int particleRadius = 4;
  float particleBounciness = 0.4f;

  int worldMeters = 10;
  float ndcPerMeter = 2.0f / worldMeters;

  vec2 gravity = vec2(0.0f, -9.81 * deltaTime);
  particles[i].velocity += gravity;

  particles[i].position += particles[i].velocity * deltaTime;

  if(particles[i].position.x + pixelsToNDC(particleRadius, int(screenSize.x)) >= 1.0f && particles[i].velocity.x > 0.0f)
    particles[i].velocity.x *= -particleBounciness;

  if(particles[i].position.x - pixelsToNDC(particleRadius, int(screenSize.x)) <= -1.0f && particles[i].velocity.x < 0.0f)
    particles[i].velocity.x *= -particleBounciness;

  if(particles[i].position.y + pixelsToNDC(particleRadius, int(screenSize.y)) >= 1.0f && particles[i].velocity.y > 0.0f)
    particles[i].velocity.y *= -particleBounciness;

  if(particles[i].position.y - pixelsToNDC(particleRadius, int(screenSize.y)) <= -1.0f && particles[i].velocity.y < 0.0f)
    particles[i].velocity.y *= -particleBounciness;

  particles[i].position.x = clamp(particles[i].position.x, -1.0f + pixelsToNDC(particleRadius, int(screenSize.x)), 1.0f - pixelsToNDC(particleRadius, int(screenSize.x)));
  particles[i].position.y = clamp(particles[i].position.y, -1.0f + pixelsToNDC(particleRadius, int(screenSize.y)), 1.0f - pixelsToNDC(particleRadius, int(screenSize.y)));
}
