#version 450

struct Particle
{
  vec2 position;
  vec3 color;
};

layout(std430, binding = 0) buffer ParticleBuffer
{
  Particle particles[];
};

layout(push_constant) uniform PushConstants
{
  uint initialize;
  vec2 screenSize;

};

layout(local_size_x = 256) in;

uint hash(uint x)
{
  x ^= x >> 16;
  x *= 0x7feb352du;
  x ^= x >> 15;
  x *= 0x846ca68bu;
  x ^= x >> 16;
  return x;
}

float randomFloat(uint x)
{
  return float(hash(x)) / 4294967295.0f;
}

void main()
{
  uint i = gl_GlobalInvocationID.x;
  if(i >= particles.length())
    return;

  if(initialize != 0)
  {
    uint count = particles.length();
    float aspect = screenSize.x / screenSize.y;

    uint gridWidth = uint(ceil(sqrt(float(count) * aspect)));
    uint gridHeight = uint(ceil(float(count) / float(gridWidth)));
    uint x = i % gridWidth;
    uint y = i / gridWidth;

    particles[i].position = vec2(
      (float(x) + 0.5) / float(gridWidth) * 2.0 - 1.0,
      (float(y) + 0.5) / float(gridHeight) * 2.0 - 1.0
    );

    particles[i].color = vec3(
      randomFloat(i),
      randomFloat(i + 1),
      randomFloat(i + 2)
    );

    return;
  }

  // simulation code

}
