#version 450

struct Particle
{
  vec2 position;
};

layout(std430, binding = 0) buffer ParticleBuffer
{
  Particle particles[];
};

layout(push_constant) uniform PushConstants
{
  uint initialize;
  vec2 screenSize;

};

layout(local_size_x = 256) in;

void main()
{
  uint i = gl_GlobalInvocationID.x;
  if(i >= particles.length())
    return;

  if(initialize != 0)
  {
    uint count = particles.length();
    float aspect = screenSize.x / screenSize.y;

    uint gridWidth = uint(ceil(sqrt(float(count) * aspect)));
    uint gridHeight = uint(ceil(float(count) / float(gridWidth)));
    uint x = i % gridWidth;
    uint y = i / gridWidth;

    particles[i].position = vec2(
      (float(x) + 0.5) / float(gridWidth) * 2.0 - 1.0,
      (float(y) + 0.5) / float(gridHeight) * 2.0 - 1.0
    );
    return;
  }

  // simulation code

}
